AllowedOrigins:
  - http://localhost:3000
  - https://localhost:7100
  - http://localhost:5100
  - https://DotnetStarter-front.cloudey.site
  - https://DotnetStarter-front.cloudey.site
  - https://DotnetStarter-front.cloudey.site
  - https://DotnetStarter-front.cloudey.site
Identity:
  PrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAtMy5FGeNHU9dwRbXPJFAPeJ+gsc6q5b5opgHAtypjhKBH9Ko
    m9gv+K5Qu0lr9Se+Npaii9/mhgc+075QJ/cvzdq5S/rEXP++W23W+yS/RA8aSkY5
    FmIRf/lpx3yQwgYvTCqTKQhzUmGnNRu8ZB7HQJbrefXzi9kvD+T5r7A5xKf6aJOP
    9kbYIPrHjO+5rL205yPpwTOq5W5QVgl1F/wBayat6qMU0QzgDYDm7Xy/fkja6Ap7
    uxiGZtyKkzxDBQ+oy9fUmef2YQG8yjMrPCegbwyuK1WELs/A2LlJq339RgN06sro
    5lN27zwBmQib+Znx7MQWcfXsfaHIhf2Y3EeHGQIDAQABAoIBAC9AF5iJDXyc+tQV
    K5AVJ9RkhoqYFbG1Za1EDQUG9Tr/hAZ0kAMWp0bXC5s+r3uk9NWgXX+vtrfNWfKN
    mLYxKCmk4WtFcJ8baTzMwnPlISVgyw6hNpcubwNig+4SFGTYp/DAabA+GKFtivza
    sEv8LTeomYbIq+sfCekd/tEW/anyid3AhNghkH3XFpGSkA/gbolQ/6W2jEMa8WLc
    GR1tTj8nsTwmSRXjL/gG+BZvbB7Yw/kHiILszwVGSc+Sgt2hUcpt6kiuGIgDpi2C
    FQzbnX8jGG2QeMyYWiz8vZtk+lFaUqcpY4kRSUQEEFJdSZMG353au7NveBoGpnf0
    VKrlJe8CgYEA5DkiiL4BhSlFznsmNncZQhw1p49hS0R/C8A9mQm30ObHqF4y+mxZ
    CjLIWJ1PwT078iaOgd3y/KtEwxpLnDUOok6WatFYRXnxj46PFb1fJKmLouwa9b5n
    2eAPOD1buDSVpFQWTsHyGsOOjbbwNH4ga+3cvSMVHjB3kSZNe4Y4ylMCgYEAys39
    l91OcJQX4lzuClJD9CNPZdq1mBCwL3X9bF2v3PU/7yNqGTXCGqp3YvBxHK599iDy
    6+Oom00pcPKrN7Bhpk2rZ5t2G0baonkECoKjDTTyCkm69VD+OY/WNFBYAe/54WWB
    +YC7NvqJB6maQTqdOp+bC4XZguUxFZuJoecac2MCgYADnkBE6LY/dTMNHfiyHltB
    KA9Vs7k4J0LYXdjcJ0JJxo7dxXiLbdJPjhSNCxlrl9vub9wMhQdIKDLz4OPX+yNb
    QWGzGdSLbW599yWfk5wBicqT76hRww4Ebz/uhVKB7ht9OnQMFZkQAY+uAXt3aZR8
    AY5hVUANdXk/zNqnna4izwKBgDzAWCcV9FllA4Kbs/MDkbegnDg2vA9BcIXHIpND
    vVrDXNOWGEJVCEBUsE7DGB8vZixE0oA3QlrDUpazGvcjrxzSR3ZR659gKj5hYgSD
    /bQHGDpcu9Sg3ob/v3sMVlC+Qmxyq+zB01M02beh5sODe3YEOb3J6s57OajvXttR
    D2thAoGAaSVWY+N7V4BIzuBc5DiAIhy1ApDg8K88yuhw3NFtNa5R2uOouUazlHET
    Gj38Pk/c+4uxlYIBhsMgqpbC8JOVU32LBplAlEXCDN+zRhrOsZ9mbxE8arvI0Lo3
    7Jgjs9zejdvhjqyM9oaz2SUtTfbclStlUDS3BF70ho1y7VPFxL4=
    -----END RSA PRIVATE KEY-----
Logging:
  LogLevel: Debug