---
AllowedOrigins:
  - https://localhost
  - http://localhost
Identity:
  PrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAq6l0/iDN7HXr4PnJbg56o8xU5iX696ZyeheGMwRpbVrpuhCS
    nL/7ldx0Z5CI/VUnr38sTBPnzVHIfr1MNkqmhFm+xlFPW8hv9N1EMY/7TLimpLwc
    84PWYzr4TyQSLD8wLZAlNCz+dERaakZ8Ln35muwvxxIovLWlbBovNKJf7PPoBs7e
    dbVw+eDi4/Souf8szHcdDjaNYzWA+I5k+/J5YhewMxF53fAazo7CuZdhNNccUoR7
    7RbiA4Z4h7Cz3h2sxLWb677ui4+PaAXcDa2RJg5moI1b8VZeGku0gpzzV26q02vJ
    K+GbyDz9vaWvMj449fl9IoAAsjhCqhRR2bAKywIDAQABAoIBACCdneD7EqUu8pZY
    X3FNxveAR1FDPh/3vCB+f70JxY5Fi8sSgwjNYVvj+yoCSET5/QRXQW9jCNP2CgYq
    qWRXYrQa6Sh9Inrp5nu73s0b8j9thhwesdGC5yULe0puLBXEG79MeAUl12L36cXv
    hoC+5sIMxjcouBzC1p9nijiR8W/vx7j9e8bq9qztKgLfH36N65+TGpmLWt/tmRbl
    VWeUDw618ulUDNfCYzHEHEQTMND21/buNK796KwjxdHNSrkx/GnjpLBZ6rwSnjED
    MX2eCcqqxENP8gxZ6BIVHLbwAogmr2Ei53nHYORBA60GqamYqAUzV4ghsfLswEQQ
    RYo4CkECgYEA6MYpEhynbHfAHBx4SfCsQavdjJ+NmFTBp+X7oBsnpFskrbuY4Cn3
    LCiRKbQwv1fGDwCESwM8JEVQV9LwX+XpT+5E7tmZFpkjT1KaGVi5X++kGQp34XU+
    S6TQ63vwdzDtQw39U3ToXUB/zUycqB7vNkgcLmdlet9Sn1QpDhDSKEkCgYEAvMpJ
    GkyUr+PT01xPLJaOKmsMpkstGf68W+ZH2JiPKDFcu0PuPDRwxXHzHK1BXHQO+h92
    nlg+avjBEOJpEKZIejLKLYX259wb8RAMEaL0NFKxYHUvb97HJLcpZYUOJp8z3d2P
    1cCJWUOw2vTktNWViRizrmHFM5NF8+jyDrD8YnMCgYEAxckKwM8EG5As9jXip8EO
    PMbR+1jfMV5jJkyuX75zEp43Lj/GiEJgOW9G2Q64lPz512ly/2ICSjdzKwybHoD2
    m+ozPFg8Ug1RCWeAdKUE7lVrM7PHZRUAF7o1osGu8zfpgh5y7+TYQ9Q4Q7MjMV8H
    lzHycCN/AMadJ7CVKdR1HbECgYBGEb44KJw2/BQuqmAoaGizja/QOK6wqz81zK51
    0YmwnUGRr5DIf54rajOVPSi5K8ozQ2I/OvlPsqvVnHLqXw0fbaJkawhM3gDw48fW
    8+g3U0nKRzQoDUNUeTbAGzY5V3Vkr0snRqKzotANND9+bpdlnulxm5AZqFuaP6c3
    lLDXyQKBgE1ZEeGaBaieiVXx+QxEf5tf6wm6Ubnt0Q3bRQI13WxTMKVdvHmRmutv
    f0pBNKWsnSKCHJas+Yl7WD1FzZCGIZjeIiw7KhUQ+tTo0Lgj21FhR7RX1MnsRDBm
    i7vXRV4gNuBZtJLmo4iWrD3FEqQcCV8085rYnB1MuGwAsqY/8c4y
    -----END RSA PRIVATE KEY-----
Database:
  MainDb:
    Host: 127.0.0.1
    User: DotnetStarter_test
    Password: DotnetStarter_test
    Port: 25433
    Database: DotnetStarter_test
